# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(469, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 30, 371, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.groesse = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.groesse.setMinimum(0.01)
        self.groesse.setMaximum(2.8)
        self.groesse.setSingleStep(0.01)
        self.groesse.setObjectName("groesse")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groesse)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gewicht = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.gewicht.setMaximum(200.0)
        self.gewicht.setSingleStep(0.01)
        self.gewicht.setObjectName("gewicht")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gewicht)
        self.calculateBTN = QtWidgets.QPushButton(self.formLayoutWidget)
        self.calculateBTN.setObjectName("calculateBTN")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.calculateBTN)
        self.result_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.result_label.setObjectName("result_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.result_label)
        self.closeBTN = QtWidgets.QPushButton(self.formLayoutWidget)
        self.closeBTN.setObjectName("closeBTN")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.closeBTN)
        self.result = QtWidgets.QLabel(self.formLayoutWidget)
        self.result.setEnabled(True)
        self.result.setMaximumSize(QtCore.QSize(16777215, 16777))
        self.result.setText("")
        self.result.setObjectName("result")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.result)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "Körpergröße in m:"))
        self.label_2.setText(_translate("MainWindow", "Gewicht in kg:"))
        self.calculateBTN.setText(_translate("MainWindow", "BMI berechnen"))
        self.result_label.setText(_translate("MainWindow", "Dein BMI beträgt:"))
        self.closeBTN.setText(_translate("MainWindow", "Programm schließen"))
